services:
  discord-bot:
    image: ghcr.io/gwillis442/randomdiscordbot2:main
    pull_policy: always
    container_name: randomdiscordbot2
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
