services:
  discord-bot:
    build:
      context: .
      dockerfile: DockerFile
    image: gwillis442/randomdiscordbot2:latest
    container_name: randomdiscordbot2
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
